# Generated by Django 6.0 on 2025-12-29 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='shop name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='status')),
                ('email', models.EmailField(max_length=254, verbose_name='shop email')),
                ('phone', models.CharField(max_length=20, verbose_name='shop phone')),
                ('address', models.TextField(verbose_name='full address')),
                ('city', models.CharField(default='Addis Ababa', max_length=100, verbose_name='city')),
                ('region', models.CharField(default='Addis Ababa', max_length=100, verbose_name='region')),
                ('country', models.CharField(default='Ethiopia', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('opening_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=200, verbose_name='opening hours')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='delivery available')),
                ('pickup_available', models.BooleanField(default=True, verbose_name='pickup available')),
                ('base_wash_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='base wash price')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='shop logo')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='shop_banners/', verbose_name='banner image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(limit_choices_to={'user_type': 'shop_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'laundry shop',
                'verbose_name_plural': 'laundry shops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cloth_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['city', 'status'], name='api_shop_city_7c7265_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='api_shop_latitud_c6d9cd_idx'),
        ),
    ]
