# Generated by Django 6.0 on 2025-12-29 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_owner_user_date_joined_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='base_wash_price',
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'shop_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
