# Generated by Django 6.0 on 2025-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='shop name'),
        ),
    ]
